/* Frame generation: the fixed part of a frame as it is recorded. Every internal image lives in
 * VK_IMAGE_LAYOUT_GENERAL for its whole life and the passes are separated by one global memory
 * barrier each. */

#include "framegen_internal.h"

static void to_general(struct afmf_device *dev, VkCommandBuffer cmd, VkImage image)
{
    VkImageMemoryBarrier barrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT |
                         VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .image = image,
        .subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1},
    };
    dev->fns.cmd_pipeline_barrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                                  VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT |
                                      VK_PIPELINE_STAGE_TRANSFER_BIT,
                                  0, 0, NULL, 0, NULL, 1, &barrier);
}

static void clear_zero(struct afmf_device *dev, VkCommandBuffer cmd, VkImage image)
{
    VkClearColorValue zero = {{0, 0, 0, 0}};
    VkImageSubresourceRange range = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    dev->fns.cmd_clear_color_image(cmd, image, VK_IMAGE_LAYOUT_GENERAL, &zero, 1, &range);
}

/* First use: every internal image to GENERAL, and the detector state cleared as the SDK does on
 * reset (a fresh luma history reads as black, which the first search treats as no motion). */
void afmf_framegen_initialize(struct afmf_device *dev, struct afmf_framegen *fg, VkCommandBuffer cmd)
{
    if (fg->color_half.image != VK_NULL_HANDLE)
        to_general(dev, cmd, fg->color_half.image);
    for (uint32_t p = 0; p < 2; p++) {
        to_general(dev, cmd, fg->color[p].image);
        for (uint32_t k = 0; k < AFMF_LEVELS; k++) {
            to_general(dev, cmd, fg->luma[p][k].image);
            to_general(dev, cmd, fg->flow[p][k].image);
            clear_zero(dev, cmd, fg->luma[p][k].image);
        }
    }
    to_general(dev, cmd, fg->flow_out.image);
    if (fg->output.image != VK_NULL_HANDLE) /* absent with direct output */
        to_general(dev, cmd, fg->output.image);
    to_general(dev, cmd, fg->scd_histogram.image);
    to_general(dev, cmd, fg->scd_previous_histogram.image);
    to_general(dev, cmd, fg->scd_temp.image);
    to_general(dev, cmd, fg->scd_output.image);
    clear_zero(dev, cmd, fg->scd_histogram.image);
    clear_zero(dev, cmd, fg->scd_previous_histogram.image);
    clear_zero(dev, cmd, fg->scd_temp.image);
    clear_zero(dev, cmd, fg->scd_output.image);
    afmf_sync(dev, cmd);
    fg->initialized = true;
}

void afmf_framegen_write_constants(struct afmf_framegen *fg, uint32_t slot, uint32_t level_count)
{
    for (uint32_t k = 0; k < fg->max_levels; k++) { /* levels above are never dispatched */
        struct cb_of of = {
            .input_luma_resolution = {(int32_t)fg->of_extent.width, (int32_t)fg->of_extent.height},
            .pyramid_level = k,
            .pyramid_level_count = level_count,
            .frame_index = fg->frame_index,
            .backbuffer_transfer_function = fg->transfer_function,
            .min_max_luminance = {fg->min_luminance, fg->max_luminance},
        };
        memcpy(fg->cb_mapped + afmf_cb_offset(fg, slot, k), &of, sizeof of);
    }
    /* The scene change detector histograms the level-0 luma, as the SDK does, so it runs
     * alongside the pyramid instead of after it (record_flow). */
    struct cb_of scd = {
        .input_luma_resolution = {(int32_t)fg->luma_size[0].width, (int32_t)fg->luma_size[0].height},
        .pyramid_level = 0,
        .pyramid_level_count = level_count,
        .frame_index = fg->frame_index,
        .backbuffer_transfer_function = fg->transfer_function,
        .min_max_luminance = {fg->min_luminance, fg->max_luminance},
    };
    memcpy(fg->cb_mapped + afmf_cb_offset(fg, slot, AFMF_CB_SCD), &scd, sizeof scd);

    /* ffxSpdSetup for the whole flow surface, 64x64 tiles, 6 mips generated by the pass. */
    uint32_t tiles_x = (fg->of_extent.width - 1) / 64 + 1;
    uint32_t tiles_y = (fg->of_extent.height - 1) / 64 + 1;
    struct cb_spd spd = {
        .mips = 6,
        .num_work_groups = tiles_x * tiles_y,
        .work_group_offset = {0, 0},
        .num_work_groups_pyramid = tiles_x * tiles_y,
    };
    memcpy(fg->cb_mapped + afmf_cb_offset(fg, slot, AFMF_LEVELS), &spd, sizeof spd);
}

void afmf_framegen_copy_whole(struct afmf_device *dev, VkCommandBuffer cmd, VkImage src,
                              VkImageLayout src_layout, VkImage dst, VkImageLayout dst_layout,
                              VkExtent2D extent)
{
    VkImageCopy region = {
        .srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1},
        .dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1},
        .extent = {extent.width, extent.height, 1},
    };
    dev->fns.cmd_copy_image(cmd, src, src_layout, dst, dst_layout, 1, &region);
}

void afmf_framegen_set_levels(struct afmf_framegen *fg, uint32_t levels)
{
    fg->levels = levels < 5u ? 5u : levels > fg->max_levels ? fg->max_levels : levels;
}

uint32_t afmf_framegen_max_levels(const struct afmf_framegen *fg)
{
    return fg->max_levels;
}

/* Records the interpolated frame with `set` (which names the output image). */
void afmf_framegen_record_interpolate(struct afmf_device *dev, struct afmf_framegen *fg,
                                      VkCommandBuffer cmd, uint32_t slot, VkDescriptorSet set,
                                      enum variant variant)
{
    const struct afmf_framegen_pipelines *pl = dev->framegen_pipelines;
    uint32_t out_w = fg->extent.width, out_h = fg->extent.height;
    struct interpolate_push push = {
        .size = {(int32_t)out_w, (int32_t)out_h},
        .block = (int32_t)AFMF_FLOW_BLOCK,
        .fallback = afmf_config_get()->fast_motion == AFMF_RESPONSE_BLENDED_FRAMES ? 1 : 0,
        .max_motion = AFMF_MAX_TRUSTED_MOTION,
        .flow_scale = (float)fg->flow_scale,
        /* One 8-bit level: HUD text is drawn after anti-aliasing and repeats exactly. */
        .hud_threshold = afmf_config_get()->hud_detect ? 1.0f / 255.0f : 0.0f,
    };
    dev->fns.cmd_push_constants(cmd, pl->layouts[PASS_INTERPOLATE], VK_SHADER_STAGE_COMPUTE_BIT, 0,
                                (uint32_t)sizeof push, &push);
    afmf_dispatch(dev, cmd, pl->interpolate[variant], pl->layouts[PASS_INTERPOLATE], set, NULL, 0,
                  (out_w + 7) / 8, (out_h + 7) / 8, 1);
    afmf_framegen_profiler_mark(dev, fg, cmd, slot, STAGE_INTERPOLATE);
}

/* The fixed part of a frame: luma, pyramid, scene change detector, then, with a companion, the
 * coarse-to-fine search and (unless the output is direct, which names the target) the
 * interpolated frame into fg->output. Depends only on the slot (constants region), the parity
 * (descriptor sets), `companion` and `levels`. */
void afmf_framegen_record_flow(struct afmf_device *dev, struct afmf_framegen *fg, VkCommandBuffer cmd,
                               uint32_t slot, uint32_t p, uint32_t levels, bool companion)
{
    const struct afmf_framegen_pipelines *pl = dev->framegen_pipelines;
    uint32_t w = fg->of_extent.width, h = fg->of_extent.height; /* optical flow dimensions */
    uint32_t of0 = afmf_cb_offset(fg, slot, 0);
    if (!fg->ingest_direct) /* otherwise the ingest pass wrote the luma with the colour */
        afmf_dispatch(dev, cmd, pl->pipelines[PASS_PREPARE_LUMA], pl->layouts[PASS_PREPARE_LUMA],
                      fg->sets[p][SET_PREPARE], &of0, 1, ((w + 1) / 2 + 15) / 16,
                      ((h + 1) / 2 + 15) / 16, 1);
    afmf_framegen_profiler_mark(dev, fg, cmd, slot, STAGE_PREPARE);

    /* The pyramid (reads luma 0, writes levels 1-6) and the detector's histogram (reads luma 0)
     * are independent: no barrier between them, so they share the GPU. */
    uint32_t pyramid_offsets[2] = {of0, afmf_cb_offset(fg, slot, AFMF_LEVELS)};
    afmf_dispatch_pass(dev, cmd, pl->pipelines[PASS_PYRAMID], pl->layouts[PASS_PYRAMID],
                       fg->sets[p][SET_PYRAMID], pyramid_offsets, 2, (w - 1) / 64 + 1,
                       (h - 1) / 64 + 1, 1, false);
    uint32_t ofscd = afmf_cb_offset(fg, slot, AFMF_CB_SCD);
    uint32_t strata_width = (fg->luma_size[0].width / 4) / AFMF_HISTOGRAMS_PER_DIM;
    afmf_dispatch(dev, cmd, pl->pipelines[PASS_SCD_HISTOGRAM], pl->layouts[PASS_SCD_HISTOGRAM],
                  fg->sets[p][SET_SCD_HISTOGRAM], &ofscd, 1, (strata_width + 31) / 32, 16,
                  AFMF_HISTOGRAMS_PER_DIM * AFMF_HISTOGRAMS_PER_DIM);
    afmf_framegen_profiler_mark(dev, fg, cmd, slot, STAGE_PYRAMID);

    /* The detector's divergence (nine groups) completes before the coarsest search: that
     * search returns early on a cut, and a group whose lanes read the verdict while the
     * detector was still writing it would split at its next barrier (a GPU hang on Intel). */
    afmf_dispatch(dev, cmd, pl->pipelines[PASS_SCD_DIVERGENCE], pl->layouts[PASS_SCD_DIVERGENCE],
                  fg->sets[p][SET_SCD_DIVERGENCE], &of0, 1,
                  AFMF_HISTOGRAMS_PER_DIM * AFMF_HISTOGRAMS_PER_DIM, AFMF_HISTOGRAM_SHIFTS, 1);

    for (uint32_t k = companion ? levels : 0; k-- > 0;) {
        uint32_t ofk = afmf_cb_offset(fg, slot, k);
        uint32_t luma_w = fg->luma_size[k].width, luma_h = fg->luma_size[k].height;
        afmf_dispatch(dev, cmd, pl->pipelines[PASS_SEARCH], pl->layouts[PASS_SEARCH],
                      fg->sets[p][SET_SEARCH + k], &ofk, 1, ((luma_w + 3) / 4 * 16 + 63) / 64,
                      (luma_h + 15) / 16, 1);
        afmf_framegen_profiler_mark(dev, fg, cmd, slot, STAGE_SEARCH);
        afmf_dispatch(dev, cmd, pl->pipelines[PASS_FILTER], pl->layouts[PASS_FILTER],
                      fg->sets[p][SET_FILTER + k], &ofk, 1, (fg->flow_size[k].width + 15) / 16,
                      (fg->flow_size[k].height + 3) / 4, 1);
        afmf_framegen_profiler_mark(dev, fg, cmd, slot, STAGE_FILTER);
        if (k > 0) {
            afmf_dispatch(dev, cmd, pl->pipelines[PASS_SCALE], pl->layouts[PASS_SCALE],
                          fg->sets[p][SET_SCALE + k - 1], &ofk, 1,
                          (fg->flow_size[k - 1].width + 3) / 4, (fg->flow_size[k - 1].height + 3) / 4,
                          1);
            afmf_framegen_profiler_mark(dev, fg, cmd, slot, STAGE_SCALE);
        }
    }

    /* The frame in between, into fg->output. */
    if (companion && !fg->direct)
        afmf_framegen_record_interpolate(dev, fg, cmd, slot, fg->sets[p][SET_INTERPOLATE], fg->variant);
}
