# Turns SPIR-V files into one C header of uint32_t arrays, so the layer carries its shaders and
# needs no files on disk at run time. Invoked as a script:
#   cmake -DOUTPUT=<header> -DINPUTS=<a.spv;b.spv> -P embed_spirv.cmake
# Each array is named after the file (afmf_interpolate_rgba8.spv -> afmf_interpolate_rgba8_spv).

if(NOT OUTPUT OR NOT INPUTS)
    message(FATAL_ERROR "embed_spirv.cmake needs OUTPUT and INPUTS")
endif()
string(REPLACE "|" ";" INPUTS "${INPUTS}") # the caller joins with | so the list survives the command line

set(header "/* Generated by cmake/embed_spirv.cmake; do not edit. */\n#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n")
foreach(input IN LISTS INPUTS)
    get_filename_component(name "${input}" NAME)
    string(REGEX REPLACE "[^A-Za-z0-9]" "_" symbol "${name}")
    file(READ "${input}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR word_count "${hex_length} / 8")
    # SPIR-V is a stream of little-endian 32-bit words: regroup the byte hex pairs accordingly.
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," words "${hex}")
    string(APPEND header "static const uint32_t ${symbol}[] = {${words}};\n")
    string(APPEND header "static const size_t ${symbol}_size = ${word_count} * sizeof(uint32_t);\n\n")
endforeach()
file(WRITE "${OUTPUT}" "${header}")
